### ISSUE TITLE
Use usbipd JSON output

### ISSUE THREAD

**Issue by dorssel** [dushanabe/wslusbip#1]
Very nice extension!

I recommend that you use the JSON output of `usbipd state`, instead of parsing the (possibly truncated) output of `usbipd wsl list`.

See https://github.com/dorssel/usbipd-win/wiki/Automation

PS: Would you like me to put this in the main README of `usbipd-win`, just like the GUI tool?

**Comment by dushanabe** [comment]
Thank you, 

I have updated the code to use usbipd instead in v0.2.0.

I did notice a small issue when parsing JSON output from usbipd state where JSON parsing was complaining about incorrect escape character for '\\' was able to work around the issue by adding another set of '\\'.

I would be more than happy if you put this in the README. usbipd has been a huge time saver for me and other colleagues at work so Thank you!
